### ISSUE TITLE
Gracefully handle DLLs that had icons moved to .mun files (Windows 10 1903+)

### ISSUE THREAD

**Issue by RixInGithub** [jlu5/icoextract#11]
**Code**:
```py
import icoextract as icns

ext = icns.IconExtractor(r"C:\Windows\System32\SHELL32.dll")
extractor.export_icon("foldIcon.ico", num=3)
print("Icon extracted successfully.")
```
**Error**:
```diff
- Traceback (most recent call last):
-   File "C:\Users\user\Downloads\whistle\icns.py", line 3, in <module>
-     ext = icns.IconExtractor(r"C:\Windows\System32\SHELL32.dll")
-           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-   File "C:\Users\user\AppData\Local\Programs\Python\Python311-32\Lib\site-packages\icoextract\__init__.py", line 56, in __init__
-     raise NoIconsAvailableError("File has no group icon resources")
- icoextract.NoIconsAvailableError: File has no group icon resources
```

**Comment by jlu5** [comment]
What Windows version is this?

**Comment by jlu5** [comment]
And what version of the pefile library do you have installed?

e.g.
```
>>> import pefile
>>> pefile
<module 'pefile' from 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pefile.py'>
>>> pefile.__version__
'2023.2.7'
```

**Comment by RixInGithub** [comment]
@jlu5 Windows 10, and also, as per `pip list`, `2023.2.7`

**Comment by jlu5** [comment]
Are you running a 32-bit version of Python on a 64-bit Windows installation by any chance? (I notice the Python311-32 part of the path). If so maybe Windows' [file system redirector](https://learn.microsoft.com/en-us/windows/win32/winprog64/file-system-redirector) is confusing the extractor.

Does it work if you copy shell32.dll to a different folder (eg on the desktop) and try to extract from that?

**Comment by matcracker** [comment]
Hi, I got the same error today when reading the imageres.dll file. Same PE version (2023.2.7), running Windows 10 64-bit and python 3.11.3 64 bit. I also tried to move the file on desktop but the exception remains. Any other suggestion?

**Comment by matcracker** [comment]
I found the issue, I need to use the files .mun which are located at `C:\Windows\SystemResources\imageres.dll.mun`

**Comment by jlu5** [comment]
Ok, yeah, all the icons for system libraries got moved to a new location in Windows 10 1903: https://superuser.com/questions/1480268/icons-no-longer-in-imageres-dll-in-windows-10-1903-4kb-file

I'm not sure if the new DLLs actually embed a reference to the .mun files, or if the system implicitly looks up the right file based on the DLL name. If the latter is true, there's not much icoextract can do other than make a guess.

**Comment by RixInGithub** [comment]
> Ok, yeah, all the icons for system libraries got moved to a new location in Windows 10 1903: https://superuser.com/questions/1480268/icons-no-longer-in-imageres-dll-in-windows-10-1903-4kb-file
> 
> I'm not sure if the new DLLs actually embed a reference to the .mun files, or if the system implicitly looks up the right file based on the DLL name. If the latter is true, there's not much icoextract can do other than make a guess.


My version of the `C:\Windows\SystemResources\imageres.dll.mun` file starts off with the magic bytes of "MZ", typically an executable or a .DLL

EDIT: It works!
EDIT #2: Now I just have to search up the code to set up a different size :eyes:

**Comment by jlu5** [comment]
Yes the new .mun files are also PE, so the extractor works out of the box on them.
