### ISSUE TITLE
FR: Transparent background

### ISSUE THREAD

**Issue by tim-gromeyer** [jlu5/icoextract#12]
Hello :)

Great project! It works damm well. But I have 1, no 2 problems:

The icons look like this, I'm 100% sure that this is not correct. The background is not transparent (problem 1) and some exe's have this strange looking standard icon (problem 2). Just take a look for yourself: 
![image](https://github.com/jlu5/icoextract/assets/58736434/4514d85b-c81c-4536-9f19-999048c2520c)

Besides this it's perfect! Thank you for your work, that really is a great project and should be installed by default if you install wine!

Best, Tim Gromeyer

**Comment by jlu5** [comment]
Thanks for your interest!

icoextract definitely does support (ie preserve) transparency in icons, but we don't have much control over how the resulting thumbnails are displayed in the file manager. The easiest way to verify whether icoextract is working correctly is to run the command line tools manually:

- `icoextract file.exe output.ico` to export a raw icon, which you can then load in an editor like GIMP to inspect 
- `exe-thumbnailer file.exe output.png` to convert it into a PNG thumbnail that the file manager uses. (This is essentially just the first step plus an image conversion)

As for the standard icon showing up, it's not unheard of for helper apps to just keep a default icon lying around. A [quick search](https://www.google.com/search?q=acshowroom.exe&tbm=isch) shows that indeed, it looks like acshowroom.exe and friends actually have that as its program icon.

**Comment by tim-gromeyer** [comment]
Okay, so I switched to nemo and I don't habe the problem anymore. Here the extracted png: 
![AssettoCorsa](https://github.com/jlu5/icoextract/assets/58736434/87fcf68f-2b4a-431f-9627-1cdc564a0ed1)
As you can see in the following screenshot, it's a nautilus issue:
![image](https://github.com/jlu5/icoextract/assets/58736434/21db6297-1cd0-4c72-8cb7-ba055f9f9652)
