### ISSUE TITLE
Any documentation on Lib usage ?

### ISSUE THREAD

**Issue by jpele-tis** [jlu5/icoextract#14]
Hello,
I am trying to use the Python library rather than the executable. Is it possible ? Is it documented ?
I wonder what data parameters are expected: `icoextract.IconExtractor(icon_path, data=?)`:
```
class IconExtractor():
    def __init__(self, filename=None, data=None):
        ...
```

Regards,
Jimmy

**Comment by jlu5** [comment]
Right under the code you pasted it tells you what the arguments mean: https://github.com/jlu5/icoextract/blob/master/icoextract/__init__.py#L35-L40

For a library this small, I think the docstrings should suffice as demonstration? Do ask if you have other specific questions

**Comment by jpele-tis** [comment]
> Right under the code you pasted it tells you what the arguments mean: https://github.com/jlu5/icoextract/blob/master/icoextract/__init__.py#L35-L40
> 
> For a library this small, I think the docstrings should suffice as demonstration? Do ask if you have other specific questions

I probably still do not understand since I expected the library to extract from an icon instead of extracting an icon.
So data is the raw data bytes of the ico file or the source file ?

**Comment by jlu5** [comment]
> > Right under the code you pasted it tells you what the arguments mean: https://github.com/jlu5/icoextract/blob/master/icoextract/__init__.py#L35-L40
> > For a library this small, I think the docstrings should suffice as demonstration? Do ask if you have other specific questions
> 
> I probably still do not understand since I expected the library to extract from an icon instead of extracting an icon. So data is the raw data bytes of the ico file or the source file ?

No, this library only deals with extracting .ico files out of an .exe or .dll. To grab individual images out of an .ico file you should use a image converter or editor: if you're not looking for a Python solution in particular, [ImageMagick](https://imagemagick.org/script/convert.php), GIMP, even MS Paint will work in a pinch for doing this

**Comment by jpele-tis** [comment]
@jlu5 Do you think I only need Pillow to extract PNG from "Extractable Icon Files" (*.exe;*.ico;*.dll) ? Because I need to script this.

**Comment by jlu5** [comment]
If your input is an .ico file you *only* need Pillow.
If your input is an .exe or .dll you can use icoextract followed by Pillow. https://github.com/jlu5/icoextract/blob/master/icoextract/scripts/thumbnailer.py has an example of doing this

I don't think it's really correct to group these file types under one umbrella - they are significantly different and don't represent the same thing. It's not clear to me which one you're expecting as input - is it .ico, .exe/.dll, or a combination of both?

**Comment by jpele-tis** [comment]
For me any icon extractor software handle such formats `.ico,.exe,.dll` so both. 
I use https://wapt.tranquil.it/store/fr/tis-becyicongrabbers

**Comment by jpele-tis** [comment]
> I don't think it's really correct to group these file types under one umbrella - they are significantly different and don't represent the same thing. It's not clear to me which one you're expecting as input - is it .ico, .exe/.dll, or a combination of both?

You are right, so I've create another function instead, thanks.


```

def extract_png_from_ico(ico_file, png_output):
    im = Image.open(ico_file)  # Open the .ico from memory

    target_size = (48, 48)
    available_sizes = im.info.get("sizes", [])

    if target_size in available_sizes:
        im.thumbnail(target_size)
        im.save(png_output, "PNG")
        print(f"Successfully extracted {target_size[0]}x{target_size[1]} icon: {ico_file} to: {png_output}")
    else:
        error_message = (
            f"No {target_size[0]}x{target_size[1]} icon found in: {inputfile}\nPlease select another file or improve the code of this function."
        )
        raise ValueError(error_message)


def extract_png_from_bin(inputfile, outfile):
    try:
        extractor = IconExtractor(inputfile)
    except RuntimeError:
        logger.debug("Failed to extract icon for %s:", inputfile, exc_info=True)
        sys.exit(1)

    data = extractor.get_icon()
    im = Image.open(data)  # Open the .ico from memory

    target_size = (48, 48)
    available_sizes = im.info.get("sizes", [])

    if target_size in available_sizes:
        im.thumbnail(target_size)
        im.save(outfile, "PNG")
        print(f"Successfully extracted {target_size[0]}x{target_size[1]} icon: {ico_file} to: {png_output}")
    else:
        error_message = (
            f"No {target_size[0]}x{target_size[1]} icon found in: {inputfile}\nPlease select another file or improve the code of this function."
        )
        raise ValueError(error_message)

```
