### ISSUE TITLE
inefficient export (size x20)

### ISSUE THREAD

**Issue by jpele-tis** [jlu5/icoextract#16]
My export is more than 20 times less efficient than any other good app.

Command:
`C:\waptdev\wapt-packages\oracle-java8-jre-nonfree\windows\x64>"C:\Program Files (x86)\wapt\Scripts\icoextract" "C:\Program Files\Java\jre-1.8\bin\java.exe" ".\WAPT\icon.png"`

Result:
![image](https://github.com/jlu5/icoextract/assets/57767497/b2b89d3d-d407-48b3-b2d5-065f09015395)

Have you any tips to improve efficiency of the exported image ?

PS: I see that https://github.com/jlu5/icoextract/issues/13#issuecomment-1613787757 is what I need but in my opinion, it would be interesting to have a flag for sizing and make a light export by default with icoextract

**Comment by jlu5** [comment]
Hmm, this is a misunderstanding of what the icoextract script does: it always exports an .ico file, not a .png directly. To convert from .ico to .png you'll want to use an external program, or a library like PIL.

I'll update the help text to make this more clear.

**Comment by jpele-tis** [comment]
oh alright, do you think I only need Pillow to extract PNG from "Extractable Icon Files" (*.exe;*.ico;*.png, maybe more ?)
