### ISSUE TITLE
Extracted icon image is corrupted in GNOME / Nautilus preview

### ISSUE THREAD

**Issue by Faugus** [jlu5/icoextract#22]
Arch Linux, using the AUR package.

With `icoextract` installed on my system, the icons are shown correctly on Nautilus or other file managers:
![image](https://github.com/jlu5/icoextract/assets/112667550/ef44c65e-7bf9-4dc0-8dcc-6a661c83f9e5)

But if try to extract the icon with
```
[faugus@archlinux Adobe Premiere Pro 2023]$ icoextract 'Adobe Premiere Pro.exe' ~/icon-extracted/icon.ico
```
The extracted icon is distorted/corrupted:
![image](https://github.com/jlu5/icoextract/assets/112667550/63e71ad6-ea80-497b-b1ba-e88a54185bf5)
![image](https://github.com/jlu5/icoextract/assets/112667550/0e962adb-ecf2-463d-8608-1620553b8c83)

**Comment by jlu5** [comment]
Can you try opening the extracted .ico file with GIMP or some other image editor?
The .ico file's preview being corrupted might be this bug: https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues/50

**Comment by Faugus** [comment]
Just tried with GIMP and the image is being shown like this:
![image](https://github.com/jlu5/icoextract/assets/112667550/eb3a4e67-af89-4501-b8b0-4329f0d17b90)

The problem happens with some .exe and with others it doesn't:
![image](https://github.com/jlu5/icoextract/assets/112667550/61fc72f3-e4b0-4072-8bc5-65bde702d53b)

**Comment by jlu5** [comment]
The extracted output is correct: GIMP will load each icon size in the .ico file as a separate layer.

.ico files rendering incorrectly in the Nautilus preview is a gdk-pixbuf bug - there's nothing I can fix on icoextract's end.
