### ISSUE TITLE
can't extract imagers.dll, shell32.dll

### ISSUE THREAD

**Issue by xdz2333** [jlu5/icoextract#24]
when I ran ext=IconExtractor('c:/windows/system32/shell32.dll'), it said icoextract.NoIconsAvailableError: File has no group icon resources

**Comment by jlu5** [comment]
Please see the note in the README:

> Note: recent versions of Windows (Windows 10 1903+) have moved icons from system libraries (shell32.dll, etc.) into a new C:\Windows\SystemResources folder. icoextract can extract these .mun files natively, but the .dlls themselves no longer contain icons.
