### ISSUE TITLE
ImportError: No module named PIL.

### ISSUE THREAD

**Issue by SpacingBat3** [jlu5/icoextract#5]
It seems that the `Pillow` isn't dependency for your `pip` package – before installing it the following error will occur:
```
ImportError: No module named PIL
```
After installing the `Pillow` with the `pip` tool, everything seems to work fine for me.

I believe you should add it as the dependency for your `pip` package to make it less confusing for the newbies.

**Comment by jlu5** [comment]
Thanks for the report. I've added it as an optional dependency in the commit above, since Pillow isn't required for the core icon extraction (only the thumbnailer part uses it)

You should have to select it manually via `pip3 install icoextract[thumbnailer]`
