### ISSUE TITLE
Exe-thumbnailer: provide smaller icons

### ISSUE THREAD

**Issue by Miepee** [jlu5/icoextract#7]
Some executables have custom icons for each size, with different amount of detail.
It would be nice if exe-thumbnailer would provide those different images depending on the zoom level of the file manager.

Currently, only the largest image is provided, which is then scaled down.

**Comment by jlu5** [comment]
As far as I can tell, the Freedesktop.org thumbnailer specification doesn't have any support for thumbnails smaller than 128x128:
https://specifications.freedesktop.org/thumbnail-spec/thumbnail-spec-latest.html#DIRSTRUCTURE

In other words, there doesn't appear to be a standard place to write these thumbnails, even if icoextract has access to icons of the right size.

**Comment by Miepee** [comment]
Ah well.
Could it at least not downscale the 256 image to 128 (if there is one) and instead just provide 128 image instead?

**Comment by jlu5** [comment]
It already does that, when 256x256 is available but 128x128 is requested: see https://github.com/jlu5/icoextract/blob/master/icoextract/scripts/thumbnailer.py#L36-L39

**Comment by Miepee** [comment]
I may have phrased myself weirdly.
Currently, if I understand this correctly, it does this:
If a 256 image is found, but a normal one is requested, take the 256 image, scale it down to 128 (aka normal size) and provide that.

What I meant, was this:
If a normal image is requested, provide the 128 image.

Hope that's clearer.

**Comment by Miepee** [comment]
Thanks a bunch!
