### ISSUE TITLE
Conflicting files for 'tests'

### ISSUE THREAD

**Issue by Nocifer** [jlu5/icoextract#9]
Hi, I'm the AUR maintainer of icoextract. I just got notified that it has file conflicts with some other Python packages, notably python-confusables and python-baycomp, and I presume that others may be affected as well.

The error is specifically about `site-packages/tests`, e.g.:

```
error: failed to commit transaction (conflicting files)
icoextract: /usr/lib/python3.10/site-packages/tests/__init__.py exists in filesystem (owned by python-confusables)
icoextract: /usr/lib/python3.10/site-packages/tests/__pycache__/__init__.cpython-310.opt-1.pyc exists in filesystem (owned by python-confusables)
icoextract: /usr/lib/python3.10/site-packages/tests/__pycache__/__init__.cpython-310.pyc exists in filesystem (owned by python-confusables)
```

What may be done to resolve such a conflict?

**Comment by UltLight** [comment]
I am getting the same error, but for spotdl
```
error: failed to commit transaction (conflicting files)
icoextract: /usr/lib/python3.10/site-packages/tests/__init__.py exists in filesystem (owned by python-spotdl)
icoextract: /usr/lib/python3.10/site-packages/tests/__pycache__/__init__.cpython-310.opt-1.pyc exists in filesystem (owned by python-spotdl)
icoextract: /usr/lib/python3.10/site-packages/tests/__pycache__/__init__.cpython-310.pyc exists in filesystem (owned by python-spotdl)
```

**Comment by Nocifer** [comment]
NVM, I just found out that per AUR guidelines it's my own responsibility to make sure `tests` is removed during setup. Feel free to close this issue.

**Comment by jlu5** [comment]
Can you check if the above commit helps? Also, thanks for doing the AUR work :)

**Comment by Nocifer** [comment]
Yup, I just tested it and it works fine.
